"use client";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowUpRight, CalendarDays, FileText, LogOut, ShieldCheck } from "lucide-react";
import { authClient } from "@/lib/auth-client";
import { api } from "@/lib/api-client";
import { money, date } from "@/lib/utils";
import { profileSchema } from "@/modules/account/validation";
import { activeTerm, type MeData } from "@/modules/account/types";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { History } from "./operations-ui";
import { ClubMark } from "./site-header";
import type { z } from "zod";
export function Account() {
  const client = useQueryClient();
  const router = useRouter();
  const [tab, setTab] = useState("overview");
  const [securityMessage, setSecurityMessage] = useState("");
  const me = useQuery({ queryKey: ["me"], queryFn: () => api<MeData>("/api/me"), refetchInterval:5000 });
  const card = useQuery({ queryKey: ["card"], queryFn: () => api<{ qr?: string; revoked?: boolean } | null>("/api/me/card"), enabled: !!me.data });
  const cardMutation = useMutation({ mutationFn: (method: "DELETE" | "POST") => api("/api/me/card", { method }), onSuccess: () => client.invalidateQueries({ queryKey: ["card"] }) });
  if (me.isPending) return <div className="site-width py-24" role="status"><div className="skeleton h-18 w-2/3"/><div className="skeleton mt-9 h-72"/><span className="sr-only">Loading your account</span></div>;
  if (me.error || !me.data) return <div className="site-width py-24"><p role="alert">{me.error?.message}</p><Button onClick={() => me.refetch()} className="mt-6">Try again</Button></div>;
  const { user, memberships, invoices } = me.data;
  const current = activeTerm(memberships);
  const expired = !current && memberships.length > 0;
  const outstanding = invoices.reduce((sum, inv) => sum + Math.max(0,inv.totalPaise - inv.allocations.reduce((s,a) => s + a.amountPaise,0) - inv.credits.reduce((s,c) => s+c.amountPaise,0)),0);
  const tabs = [{ id: "overview", label: "Overview" }, { id: "profile", label: "My profile" }, { id: "history", label: "Membership history" }, { id: "receipts", label: "Receipts & statement" }, { id: "activity", label: "Bookings & purchases" }];
  return <section className="site-width py-14 md:py-20"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow mb-5 text-orange-400">My Account</p><h1 className="section-title">Hey, {user.name.split(" ")[0]}.</h1><p className="mt-4 text-sm text-neutral-400">Your club, at a glance. <span className="ml-2 text-neutral-500">{user.championsId}</span></p></div><div className="flex gap-3">{user.role !== "MEMBER" && <Button asChild variant="outline"><Link href="/staff">Staff desk<ArrowUpRight size={16}/></Link></Button>}<Button variant="ghost" onClick={async () => { await authClient.signOut(); client.clear(); router.push("/"); router.refresh(); }}><LogOut size={16}/>Sign out</Button></div></div>
  <nav className="mt-10 flex flex-wrap gap-2 border-b border-white/10 pb-4" aria-label="Account sections">{tabs.map(item => <button key={item.id} aria-current={tab === item.id ? "page" : undefined} onClick={() => setTab(item.id)} className={`rounded px-4 py-3 text-xs ${tab === item.id ? "bg-white text-black" : "text-neutral-400 hover:text-white"}`}>{item.label}</button>)}</nav>
  {tab === "overview" && <div className="mt-10 grid gap-8 lg:grid-cols-[1.2fr_1fr]"><div><div className={`relative overflow-hidden rounded-xl border ${current?.planId === "gold" ? "border-orange-500/50 bg-gradient-to-br from-[#3b2415] via-[#211c16] to-[#131313]" : "border-white/20 bg-gradient-to-br from-[#25282c] to-[#121212]"} p-8 md:p-10`}><div className="absolute -right-24 -top-24 size-80 rounded-full border-[50px] border-white/3"/><div className="relative flex justify-between"><div className="flex items-center gap-3"><ClubMark className="text-orange-400"/><span className="brand-wordmark">CHAMPIONS<span>CLUB</span></span></div><span className="text-xs uppercase tracking-[.22em] text-orange-300">{current?.planSnapshot.name || (expired ? "Expired" : "Your club account")}</span></div><p className="mt-10 text-2xl font-medium">{user.name}</p><p className="mt-2 font-mono text-sm text-white/50">{user.championsId}</p>{current ? <div className="mt-8 flex items-end justify-between gap-4"><div><p className="text-[10px] uppercase tracking-widest text-white/40">Valid through</p><p className="mt-2 text-sm">{date(new Date(+new Date(current.endsAt)-1))}</p><p className="mt-5 text-[10px] text-white/35">Staff scan this card for your benefits.</p></div>{card.data?.qr ? <Image src={card.data.qr} width={110} height={110} alt="Your personal Champions membership QR card" className="rounded bg-white" unoptimized/> : <span className="text-xs text-neutral-400">{card.data?.revoked ? "Card revoked" : "Loading card…"}</span>}</div> : <><p className="mt-7 text-sm leading-relaxed text-white/60">{expired ? "Your membership has expired. Your games and history are still here." : "You're part of the club. A membership opens up even more."}</p><Button asChild className="mt-7"><Link href="/memberships">{expired ? "Renew your membership" : "Get a Membership"}<ArrowUpRight size={16}/></Link></Button></>}</div>
    {current && <div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-xs text-neutral-500"><span>Your QR identifies you. It does not authorize payment.</span><button className="text-neutral-300 underline" disabled={cardMutation.isPending} onClick={() => cardMutation.mutate(card.data?.revoked ? "POST" : "DELETE")}>{card.data?.revoked ? "Issue a new card" : "Revoke card"}</button></div>}{cardMutation.error && <p role="alert" className="field-error mt-3">{cardMutation.error.message}</p>}{card.error && <p role="alert" className="field-error mt-3">{card.error.message}</p>}
    <div className="mt-8 rounded-lg border border-white/10 p-6"><h2 className="text-lg">Keep the good games going.</h2><p className="soft-text mt-3 text-sm">{current ? `Your ${current.planSnapshot.name} membership gives you ${current.planSnapshot.courtDiscountBps / 100}% court, ${current.planSnapshot.shopDiscountBps / 100}% shop and ${current.planSnapshot.foodDiscountBps / 100}% clubhouse benefits.` : "Find a membership that fits your kind of play."}</p><Button asChild variant="outline" className="mt-5"><Link href="/memberships">{current ? "Renew or change plan" : "Explore memberships"}<ArrowUpRight size={16}/></Link></Button></div></div>
    <div className="space-y-5"><div className="rounded-lg border border-white/10 p-7"><div className="flex items-center gap-3"><FileText size={19} className="text-orange-400"/><h2>Your club statement</h2></div><p className="mt-7 text-4xl tracking-tight">{money(Math.max(0,outstanding))}</p><p className="mt-2 text-xs text-neutral-500">Outstanding balance across your club</p><button className="mt-6 text-sm text-orange-400" onClick={() => setTab("receipts")}>View receipts & statement →</button></div><div className="rounded-lg border border-white/10 p-7"><CalendarDays size={21} className="text-orange-400"/><h2 className="mt-4">Your next great game.</h2><p className="soft-text mt-3 text-sm">Explore the courts and find your sport. Book an hourly session or join Friday social play.</p><Link className="mt-5 inline-flex gap-2 text-sm" href="/book">Explore courts<ArrowUpRight size={16}/></Link></div><div className="rounded-lg border border-white/10 p-7"><ShieldCheck size={21} className="text-orange-400"/><h2 className="mt-4">Account security</h2><p className="soft-text mt-3 text-xs">Email verified · Sessions expire after seven days</p><Button className="mt-5" variant="outline" size="sm" onClick={async () => { try { const result = await authClient.revokeOtherSessions(); setSecurityMessage(result.error?.message || "All other sessions have been signed out."); } catch { setSecurityMessage("Could not revoke sessions. Try again."); } }}>Sign out other devices</Button>{securityMessage && <p role="status" className="mt-4 text-xs text-orange-300">{securityMessage}</p>}</div></div></div>}
  {tab === "profile" && <ProfileForm user={user}/>}
  {tab === "history" && <div className="mt-10"><h2 className="text-2xl">Your membership journey</h2>{!memberships.length ? <p className="soft-text mt-6">Your first membership is waiting for you.</p> : <div className="mt-7 space-y-4">{memberships.map(t => <article key={t.id} className="flex flex-wrap items-center justify-between gap-4 rounded border border-white/10 p-6"><div><h3 className="font-medium">{t.planSnapshot.name}</h3><p className="mt-2 text-xs text-neutral-500">{date(t.startsAt)} — {date(new Date(+new Date(t.endsAt)-1))}</p></div><span className="text-sm">{money(t.pricePaise)}</span><span className="text-xs text-orange-300">{t.status === "SUPERSEDED" ? "Plan changed" : new Date(t.startsAt) > new Date() ? "Upcoming term" : new Date(t.endsAt) <= new Date() ? "Expired" : "Active"}</span></article>)}</div>}</div>}
  {tab === "receipts" && <div className="mt-10"><div className="flex flex-wrap justify-between gap-6"><h2 className="text-2xl">Receipts & statement</h2><span className="text-sm text-neutral-400">Outstanding: {money(Math.max(0,outstanding))}</span></div>{!invoices.length ? <p className="soft-text mt-7">Your receipts will appear here after your first purchase.</p> : <div className="mt-7 space-y-4">{invoices.map(inv => <Link key={inv.id} href={`/account/receipts/${inv.id}`} className="flex flex-wrap items-center justify-between gap-4 rounded border border-white/10 p-6 transition-colors hover:bg-white/5"><div><h3 className="text-sm">{inv.number}</h3><p className="mt-2 text-xs text-neutral-500">{inv.department.toLowerCase()} · {date(inv.issuedAt)}</p></div><div className="text-right"><p>{money(inv.totalPaise)}</p><p className="mt-2 text-xs text-neutral-500">{inv.allocations.some(a => a.payment.source === "LOCAL_SIMULATED") ? "Local simulated payment" : "Recorded payment"}</p></div><ArrowUpRight size={18}/></Link>)}</div>}</div>}
  {tab === "activity" && <History/>}
  </section>;
}
function ProfileForm({ user }: { user: MeData["user"] }) {
  const client = useQueryClient();
  const router = useRouter();
  const { register, handleSubmit, formState: { errors } } = useForm<z.infer<typeof profileSchema>>({ resolver: zodResolver(profileSchema), defaultValues: { name: user.name, phone: user.phone || "", dateOfBirth: user.dateOfBirth?.slice(0,10) || "" } });
  const mutation = useMutation({ mutationFn: (data: z.infer<typeof profileSchema>) => api("/api/me", { method: "PATCH", body: JSON.stringify(data) }), onSuccess: async () => { await client.invalidateQueries({ queryKey: ["me"] }); router.refresh(); } });
  return <form className="mt-10 max-w-xl space-y-6" onSubmit={handleSubmit(data => mutation.mutate(data))}><h2 className="text-2xl">Make it yours.</h2><div><label htmlFor="profile-name">Full name</label><Input id="profile-name" autoComplete="name" className="mt-2" {...register("name")}/>{errors.name && <p className="field-error">{errors.name.message}</p>}</div><div><label htmlFor="profile-email">Email address</label><Input id="profile-email" value={user.email} disabled className="mt-2"/><p className="mt-2 text-xs text-neutral-500">Your verified account email.</p></div><div><label htmlFor="profile-phone">Phone number</label><Input id="profile-phone" type="tel" autoComplete="tel" className="mt-2" {...register("phone")}/>{errors.phone && <p className="field-error">{errors.phone.message}</p>}</div><div><label htmlFor="profile-birth">Date of birth</label><Input id="profile-birth" type="date" max={new Date().toISOString().slice(0,10)} autoComplete="bday" className="mt-2 [color-scheme:dark]" {...register("dateOfBirth")}/><p className="mt-2 text-xs text-neutral-500">Required for Junior membership eligibility.</p>{errors.dateOfBirth && <p className="field-error">{errors.dateOfBirth.message}</p>}</div>{mutation.error && <p className="field-error" role="alert">{mutation.error.message}</p>}{mutation.isSuccess && <p role="status" className="text-sm text-orange-300">Profile saved.</p>}<Button disabled={mutation.isPending}>{mutation.isPending ? "Saving…" : "Save profile"}</Button></form>;
}
