import Link from "next/link";
import { ArrowUpRight, Check } from "lucide-react";
import { money } from "@/lib/utils";
import { Button } from "./ui/button";
import { termDays, termPrice, type BillingPeriod } from "@/modules/membership/terms";
export type PlanView = { id: string; name: string; description: string; pricePaise: number; durationDays: number; courtDiscountBps: number; shopDiscountBps: number; foodDiscountBps: number; freeSessionsWeek: number; juniorOnly: boolean; planVersion: string };
export function PlanCard({ plan, period = "quarterly", children }: { plan: PlanView; period?: BillingPeriod; children?: React.ReactNode }) {
  return <article className={`plan-card ${plan.id === "gold" ? "gold" : ""} flex h-full flex-col`}><div className="flex items-center justify-between"><h3 className="text-2xl font-medium">{plan.name}</h3>{plan.id === "gold" && <span className="text-[10px] font-semibold uppercase tracking-widest text-orange-400">All in</span>}</div><p className="mt-3 text-sm text-neutral-400">{plan.description}</p><p className="mb-1 mt-8 text-4xl font-medium tracking-tight">{money(termPrice(plan.pricePaise, period))}</p><p className="text-xs text-neutral-500">per {termDays(period, plan.durationDays)} days · taxes included</p><div className="my-7 h-px bg-white/10"/><ul className="mb-9 flex-1 space-y-4 text-sm text-neutral-300">{[`${plan.courtDiscountBps / 100}% off court bookings`, `${plan.shopDiscountBps / 100}% off at The Champions Shop`, `${plan.foodDiscountBps / 100}% off at the clubhouse`, plan.freeSessionsWeek ? `${plan.freeSessionsWeek} complimentary sessions per week` : "Access to all four sports", plan.juniorOnly ? "For players under 18" : "Your personal digital club card"].map(text => <li key={text} className="flex gap-3"><Check size={16} className="shrink-0 text-orange-400"/>{text}</li>)}</ul>{children || <Button asChild variant={plan.id === "gold" ? "default" : "outline"}><Link href={`/memberships?plan=${plan.id}`}>Explore {plan.name}<ArrowUpRight size={16}/></Link></Button>}</article>;
}
