import Link from "next/link";
import { notFound } from "next/navigation";
import { pageUser } from "@/lib/access";
import { ownedInvoice } from "@/modules/account/queries";
import { money, date } from "@/lib/utils";
import { PrintButton } from "@/components/print-button";
export default async function Receipt({ params }: { params: Promise<{ id: string }> }) {
  const user = await pageUser();
  const { id } = await params;
  const invoice = await ownedInvoice(user.id, id);
  if (!invoice) notFound();
  const paid = invoice.allocations.reduce((s,a) => s+a.amountPaise,0);
  return <section className="site-width py-16"><div className="mb-8 flex flex-wrap justify-between gap-4"><Link className="no-print text-sm text-neutral-400" href="/account">← My Account</Link><PrintButton/></div><article className="receipt mx-auto max-w-3xl rounded-lg bg-[#eeede7] p-7 text-[#222] md:p-12"><div className="flex flex-wrap justify-between gap-6"><div><h1 className="text-3xl font-semibold tracking-tight">Champions Club</h1><p className="mt-3 text-sm">Membership receipt · {invoice.number}</p></div><p className="text-sm">{date(invoice.issuedAt)}</p></div><div className="my-9 border-y border-black/15 py-6 text-sm"><p className="text-xs text-neutral-500">ISSUED TO</p><p className="mt-3 font-medium">{invoice.customerName}</p><p className="mt-2 text-neutral-500">{invoice.customerEmail}</p></div><div className="space-y-6">{invoice.lines.map(line => <div key={line.id} className="flex justify-between gap-8 text-sm"><div><p>{line.description}</p><p className="mt-2 text-xs text-neutral-500">{line.quantity} × {money(line.unitPaise)}</p></div><strong>{money(line.totalPaise)}</strong></div>)}</div><div className="mt-9 space-y-4 border-t border-black/15 pt-7 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{money(invoice.subtotalPaise)}</span></div><div className="flex justify-between"><span>Discount</span><span>{money(invoice.discountPaise)}</span></div><div className="flex justify-between text-lg font-semibold"><span>Total · INR</span><span>{money(invoice.totalPaise)}</span></div><div className="flex justify-between"><span>Payment allocated</span><span>{money(paid)}</span></div>{invoice.credits.map(c => <div key={c.id} className="flex justify-between"><span>Credit · {c.reason}</span><span>{money(c.amountPaise)}</span></div>)}<div className="flex justify-between"><span>Outstanding</span><span>{money(Math.max(0,invoice.totalPaise-paid-invoice.credits.reduce((s,c) => s+c.amountPaise,0)))}</span></div></div>{invoice.allocations.map(a => <div key={a.id} className="mt-7 rounded bg-black/5 p-5 text-xs leading-relaxed"><p className="font-semibold">{a.payment.source === "LOCAL_SIMULATED" ? "LOCAL TEST RECEIPT — SIMULATED PAYMENT" : a.payment.source}</p><p className="mt-2">Method: {a.payment.method} · {date(a.payment.receivedAt)}</p><p className="mt-2 break-all text-neutral-500">Reference: {a.payment.reference}</p><p className="mt-2">{a.payment.source === "LOCAL_SIMULATED" ? "No funds were collected. This receipt is for local demonstration." : "Recorded payment allocation."}</p></div>)}<p className="mt-9 text-xs text-neutral-500">Thank you for being part of Champions Club.</p></article></section>;
}
